### ISSUE TITLE
Scrape IN election results

### ISSUE THREAD

**Issue by zstumgoren** [openelections/openelections-data-in#1]
Official results appear to be spread across scrapable web pages and some not-so-friendly PDFs. Discuss strategy with @aachokey, who said he'd like to get involved with this state.

**Comment by aachokey** [comment]
Is that from the state Election Division site you're referring to?

**Comment by zstumgoren** [comment]
Hey @aachokey yep, I should have included a link to the [top-level page](http://www.in.gov/sos/elections/2400.htm) It might be worth contacting state officials directly, btw, to see if an easier-to-use data source is available. We have a metadata site that I can provide you access to where we track election dates, history of FOIAs, etc. I'll set you up on that today.

**Comment by zstumgoren** [comment]
Can you send me your email address offline @aachokey?

**Comment by aachokey** [comment]
No word from the guy who owns capitolandwashington.com and it's been a couple of weeks. Should I move forward with the PDFs that we have?

**Comment by dwillis** [comment]
Yeah, please do. To be fair, he's running a Senate campaign this year, so probably kinda busy.

**Comment by aachokey** [comment]
So I've started with 2012 and wrote a small scraper to cycle through the drop-down here: http://www.in.gov/apps/sos/primary/sos_primary12

It gathers the tables for each county separately, but I'm not 100% on the parsing just yet. The primary results for that year are stored on the site in the same way. I just wanted to touch base and see if you guys think this is a good route or if I should do this differently?

**Comment by dwillis** [comment]
Hey @aachokey: that sounds like exactly the right path to take. It's up to you whether you store the counties separately, but it might be easier to save the results in a single file.

**Comment by aachokey** [comment]
Thanks, @dwillis. I've got the scraper wrapped up and have the html tables in a separate file for each county. So far, we have the general and primary election results of 2012 and 2014. Would that be the type of thing to go into the "sources" repo?

**Comment by dwillis** [comment]
@aachokey: Thanks! It could go in a sources repo, sure. Another option would be to add HTML parsing to your scraper so that it extracts the data from the tables and writes out a CSV file with them. I'm glad to help with this; do you want to check in what you have on your fork and I can take a look?

**Comment by aachokey** [comment]
@dwillis: Sure thing! I put in a pull request with the files as well as the scraper I used. The 2012 folder also has a script I started to parse the tables to CSV. Not completed just yet though.

**Comment by dwillis** [comment]
@aachokey Thanks - will take a look.
